# Generated by Django 2.2.3 on 2019-08-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=1000)),
                ('año', models.CharField(max_length=20)),
                ('mes', models.CharField(max_length=20)),
                ('dia', models.CharField(max_length=20)),
                ('lugares', models.CharField(max_length=40)),
                ('topicos', models.CharField(max_length=500)),
            ],
        ),
    ]
