# Generated by Django 2.2.3 on 2019-08-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papers',
            old_name='lugares',
            new_name='ciudad',
        ),
        migrations.AddField(
            model_name='papers',
            name='pais',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
